name: nerfstudio1
channels:
  - nvidia/label/cuda-11.8.0
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cuda-cccl=11.8.89=0
  - cuda-command-line-tools=11.8.0=0
  - cuda-compiler=11.8.0=0
  - cuda-cudart=11.8.89=0
  - cuda-cudart-dev=11.8.89=0
  - cuda-cuobjdump=11.8.86=0
  - cuda-cupti=11.8.87=0
  - cuda-cuxxfilt=11.8.86=0
  - cuda-documentation=11.8.86=0
  - cuda-driver-dev=11.8.89=0
  - cuda-gdb=11.8.86=0
  - cuda-libraries=11.8.0=0
  - cuda-libraries-dev=11.8.0=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight=11.8.86=0
  - cuda-nsight-compute=11.8.0=0
  - cuda-nvcc=11.8.89=0
  - cuda-nvdisasm=11.8.86=0
  - cuda-nvml-dev=11.8.86=0
  - cuda-nvprof=11.8.87=0
  - cuda-nvprune=11.8.86=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvrtc-dev=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-nvvp=11.8.87=0
  - cuda-profiler-api=11.8.86=0
  - cuda-sanitizer-api=11.8.86=0
  - cuda-toolkit=11.8.0=0
  - cuda-tools=11.8.0=0
  - cuda-visual-tools=11.8.0=0
  - gds-tools=1.4.0.31=0
  - icu=75.1=he02047a_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_104
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.9.0.58=0
  - libcufile=1.4.0.31=0
  - libcufile-dev=1.4.0.31=0
  - libcurand=10.3.0.86=0
  - libcurand-dev=10.3.0.86=0
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgomp=15.2.0=h767d61c_7
  - liblzma=5.8.1=hb9d3cd8_2
  - libnpp=11.8.0.86=0
  - libnpp-dev=11.8.0.86=0
  - libnsl=2.0.1=hb9d3cd8_1
  - libnvjpeg=11.9.0.86=0
  - libnvjpeg-dev=11.9.0.86=0
  - libsqlite=3.51.0=hee844dc_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libuuid=2.41.2=he9a06e4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - nsight-compute=2022.3.0.22=0
  - openssl=3.6.0=h26f9b46_0
  - pip=25.3=pyh8b19718_0
  - python=3.10.19=h3c07f61_2_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_ha0e22de_103
  - wheel=0.45.1=pyhd8ed1ab_1
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - absl-py==2.3.1
      - addict==2.4.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - appdirs==1.4.4
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asttokens==3.0.1
      - async-lru==2.0.5
      - attrs==25.4.0
      - av==16.0.1
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - bidict==0.23.1
      - bleach==6.3.0
      - blinker==1.9.0
      - cachetools==6.2.2
      - certifi==2022.12.7
      - cffi==2.0.0
      - charset-normalizer==2.1.1
      - click==8.3.1
      - colorlog==6.10.1
      - comet-ml==3.54.2
      - comm==0.2.3
      - configargparse==1.7.1
      - configobj==5.0.9
      - contourpy==1.3.2
      - cryptography==46.0.3
      - cycler==0.12.1
      - dash==3.3.0
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - descartes==1.1.0
      - dill==0.4.0
      - docstring-parser==0.17.0
      - dulwich==0.24.10
      - embreex==2.17.7.post7
      - everett==3.1.0
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - filelock==3.19.1
      - fire==0.7.1
      - flask==3.1.2
      - fonttools==4.60.1
      - fpsample==1.0.0
      - fqdn==1.5.1
      - fsspec==2025.9.0
      - fused-bilagrid==0.0.0
      - fused-ssim==1.0.0
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - grpcio==1.76.0
      - gsplat==1.5.3
      - h11==0.16.0
      - h5py==3.15.1
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.4
      - imageio==2.37.2
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.7.0
      - ipykernel==7.1.0
      - ipython==8.37.0
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jaxtyping==0.3.3
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.6.3
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.5.0
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.9
      - lark==1.3.1
      - lazy-loader==0.4
      - lightning-utilities==0.15.2
      - lxml==6.0.2
      - manifold3d==3.3.2
      - mapbox-earcut==2.0.0
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - mediapy==1.2.4
      - mistune==3.1.4
      - mpmath==1.3.0
      - msgpack==1.1.2
      - msgpack-numpy==0.4.8
      - msgspec==0.20.0
      - multiprocess==0.70.18
      - narwhals==2.12.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nerfacc==0.5.2
      - nerfstudio==1.1.5
      - nerfview==0.1.2
      - nest-asyncio==1.6.0
      - networkx==3.3
      - ninja==1.13.0
      - nodeenv==1.9.1
      - notebook-shim==0.2.4
      - numpy==1.26.4
      - nuscenes-devkit==1.2.0
      - open3d==0.19.0
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.10.0.84
      - overrides==7.7.0
      - packaging==25.0
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - parameterized==0.9.0
      - parso==0.8.5
      - pathos==0.3.4
      - pexpect==4.9.0
      - pillow==11.3.0
      - platformdirs==4.5.0
      - plotly==6.5.0
      - plyfile==1.1.3
      - pox==0.3.6
      - ppft==1.7.7
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - protobuf==3.20.3
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pybind11==3.0.1
      - pycocotools==2.0.10
      - pycollada==0.9.2
      - pycolmap==0.0.1
      - pycparser==2.23
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pyliblzfse==0.4.1
      - pymeshlab==2025.7
      - pyngrok==7.5.0
      - pyparsing==3.2.5
      - pyquaternion==0.9.9
      - pysocks==1.7.1
      - python-box==6.1.0
      - python-dateutil==2.9.0.post0
      - python-engineio==4.12.3
      - python-json-logger==4.0.0
      - python-socketio==5.15.0
      - pytorch-msssim==1.0.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - rawpy==0.25.1
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - retrying==1.4.2
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==14.2.0
      - rpds-py==0.29.0
      - rtree==1.4.1
      - safetensors==0.7.0
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - sentry-sdk==2.46.0
      - shapely==2.0.7
      - shtab==1.8.0
      - simple-websocket==1.1.0
      - simplejson==3.20.2
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.8
      - splines==0.3.0
      - stack-data==0.6.3
      - svg-path==7.0
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorly==0.9.0
      - termcolor==3.2.0
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - timm==0.6.7
      - tinycss2==1.4.0
      - tinycudann==2.0
      - tokenizers==0.21.4
      - tomli==2.3.0
      - torch==2.1.2+cu118
      - torch-fidelity==0.3.0
      - torchmetrics==1.8.2
      - torchvision==0.16.2+cu118
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.49.0
      - trimesh==4.10.0
      - triton==2.1.0
      - typeguard==4.4.4
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tyro==0.9.35
      - tzdata==2025.2
      - uri-template==1.3.0
      - urllib3==2.5.0
      - vhacdx==0.0.9
      - viser==0.2.7
      - wadler-lindig==0.1.7
      - wandb==0.23.0
      - wcwidth==0.2.14
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - websockets==15.0.1
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.15
      - wrapt==2.0.1
      - wsproto==1.3.2
      - wurlitzer==3.1.1
      - xatlas==0.0.11
      - xxhash==3.6.0
      - yourdfpy==0.0.58
      - zipp==3.23.0
prefix: /opt/conda/envs/nerfstudio1


